server:
  port: 83

spring:
  application:
    name: cloud-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 114.132.70.228:8848

nacos-server-url: http://nacos-payment-provider