server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 114.132.70.228:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'