server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://PaymentApp          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
##            - After=2022-06-19T19:56:41.283+08:00[Asia/Shanghai]
##             - Cookie=username,dty   #cookie，匹配正则表达式  "username=dty"
##             - Header=X-Request-Id, \d+ #请求头参数 Request-Id 请求头参数X-Request-Id为整数
##            - Method=GET  #匹配方法名
##            - Query=green #The preceding route matches if the request contained a green query parameter.
#            - Query=green gree.
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka